### ISSUE TITLE
Circular dependency caused by nginx plugin

### ISSUE THREAD

**Issue by adamretter** [voxpupuli/puppet-letsencrypt#331]
## Affected Puppet, Ruby, OS and module versions/distributions

- puppet-letsencrypt version: 10.0.0
- puppetserver version: 8.2.3
- puppet version: 7.24.0

## How to reproduce (e.g Puppet code you use)

My node's YAML:
```yaml
classes:
   - profile::letsencrypt

letsencrypt::email: 'adam.retter@nationalarchives.gov.uk'

letsencrypt::certificates:
  'www.catalogue.nationalarchives.gov.uk':
    domains:
      - 'www.catalogue.nationalarchives.gov.uk'
    plugin: nginx
    manage_cron: false
```

My `letsencrypt.pp` role
```puppet
class profile::letsencrypt {
  class { 'letsencrypt':
    package_ensure => latest,
    configure_epel => false,  # NOTE(AR) this is managed by our EPEL profile instead
    require        => Class['profile::epel'],
  }
  class { 'letsencrypt::plugin::nginx':
    manage_package => true,
    package_name   => 'python2-certbot-nginx',
  }
}
```

## What are you seeing

When the `plugin: nginx` is set in my YAML I get this error at the Puppet Agent:

```
puppet-agent[4931]: Found 1 dependency cycle:
puppet-agent[4931]: (Exec[letsencrypt certonly www.catalogue.nationalarchives.gov.uk] => Letsencrypt::Certonly[www.catalogue.nationalarchives.gov.uk] => Class[Letsencrypt] => Class[Letsencrypt::Plugin::Nginx] => Package[python2-certbot-nginx] => Class[Letsencrypt::Plugin::Nginx] => Letsencrypt::Certonly[www.catalogue.nationalarchives.gov.uk] => Exec[letsencrypt certonly www.catalogue.nationalarchives.gov.uk])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
puppet-agent[4931]: Failed to apply catalog: One or more resource dependency cycles detected in graph
systemd[1]: Stopping Puppet agent...
```

## What behaviour did you expect instead

That it works without error!
